# Generated by Django 5.0.7 on 2024-07-17 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_person_missing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('owner_name', models.CharField(max_length=30)),
                ('license_no', models.IntegerField()),
                ('make_model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('rc_book', models.ImageField(upload_to='media/')),
                ('license_image', models.ImageField(upload_to='media/')),
                ('vehicle_image', models.ImageField(upload_to='media/')),
                ('issue', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'PENDING'), (2, 'ACCEPTED'), (3, 'APPROVED'), (4, 'REJECTED')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delete_status', models.IntegerField(choices=[(1, 'Live'), (0, 'Delete')], default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_management', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
