# Generated by Django 5.0.7 on 2024-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_vehicle_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp_allocation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
