# Generated by Django 5.0.7 on 2024-07-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_camp_allocation_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_missing',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='person_missing',
            name='status',
            field=models.IntegerField(choices=[(1, 'SEARCHING'), (2, 'FOUNDED')], default=0),
        ),
    ]
