# Generated by Django 5.0.7 on 2024-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_person_missing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_missing',
            name='status',
            field=models.CharField(choices=[(1, 'SEARCHING'), (2, 'FOUNDED')], default=1, max_length=100),
        ),
    ]
