# Generated by Django 5.0.7 on 2024-07-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_person_missing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='camp',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
