# Generated by Django 5.0.7 on 2024-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_camp_alternate_phone_alter_camp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person_missing',
            name='camp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
