# Generated by Django 5.0.7 on 2024-07-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_volunteer_camp_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_camp_allocation',
            name='dob',
        ),
    ]
