# Generated by Django 5.0.7 on 2024-07-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_volunteer_camp_allocation_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_camp_allocation',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
