# Generated by Django 5.0.7 on 2024-07-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_volunteer_camp_allocation_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_camp_allocation',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='volunteer_camp_allocation',
            name='mother_name',
        ),
        migrations.AlterField(
            model_name='volunteer_camp_allocation',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
