# Generated by Django 5.0.7 on 2024-07-25 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_remove_volunteer_camp_allocation_father_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_camp_allocation',
            name='occupation',
        ),
    ]
