# Generated by Django 5.0.7 on 2024-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_volunteer_camp_allocation_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_camp_allocation',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
