# Generated by Django 5.0.7 on 2024-07-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_volunteer_camp_allocation_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_management',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Searching', 'SEARCHING'), ('Approved', 'APPROVED'), ('Rejected', 'REJECTED'), ('Founded', 'FOUNDED')], default=0, max_length=100),
        ),
    ]
