# Generated by Django 5.0.7 on 2024-07-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_insurance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='camp_allocation',
        ),
    ]
