# Generated by Django 5.0.7 on 2024-07-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_fund_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Approved', 'APPROVED'), ('Rejected', 'REJECTED')], default=None, max_length=100),
        ),
    ]
