# Generated by Django 5.0.7 on 2024-07-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_fund_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
