# Generated by Django 5.0.7 on 2024-08-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_rescue'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_camp_allocation',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
