# Generated by Django 5.0.7 on 2024-08-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_volunteer_camp_allocation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_camp_allocation',
            name='status',
        ),
    ]
