# Generated by Django 5.0.7 on 2024-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_person_missing_district_person_missing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_station',
            name='state',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
