# Generated by Django 5.0.7 on 2024-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_police_station_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescue',
            name='state',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
