# Generated by Django 5.0.7 on 2024-08-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_rescue_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_management',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle_management',
            name='state',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
