# Generated by Django 5.0.7 on 2024-08-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_insurance_district_insurance_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_management',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.insurance'),
        ),
    ]
