# Generated by Django 5.0.7 on 2024-08-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_vehicle_management_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
