from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name="index"),
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
    path('public-register',views.public_register,name="public-register"),
    path('camp-register',views.camp_register,name="camp-register"),
    path('camp-login',views.camp_login,name="camp-login"),
    path('camp-dashborad',views.camp_dashborad,name="camp-dashborad"),
    path('policestation-register',views.policestation_register,name="policestation-register"),
    path('policestation-login',views.policestation_login,name="policestation-login"),
    path('policestation-dashboard',views.policestation_dashboard,name="policestation-dashboard"),
    path('volunteer-register',views.volunteer_register,name="volunteer-register"),
    path('volunteer-login',views.volunteer_login,name="volunteer-login"),
    path('volunteer-dashboard',views.volunteer_dashboard,name="volunteer-dashboard"),
    path('volunteer-camp-allocations',views.volunteer_camp_allocations,name="volunteer-camp-allocations"),
    path('insurance-register',views.insurance_register,name="insurance-register"),
    path('insurance-login',views.insurance_login,name="insurance-login"),
    path('insurance-dashboard',views.insurance_dashboard,name="insurance-dashboard"),
    path('gov-login',views.gov_login,name="gov-login"),
    path('public-login',views.public_login,name="public-login"),
    path('camp-details',views.camp_details,name="camp-details"),
    path('public-profile',views.public_profile,name="public-profile"),
    path('public-dashboard',views.public_dashboard,name="public-dashboard"),
    path('public-registration',views.public_registration,name="public-registration"),
    path('public-person-missing',views.person_missing,name="public-person-missing"),
    path('public-vehicle-mngt',views.public_vehicle_management,name="public-vehicle-mngt"),
    path('public-vehicle-damage',views.public_vehicle_damage,name="public-vehicle-damage"),
    path('public-vehicle-missing',views.public_vehicle_missing,name="public-vehicle-missing"),
    path('relief-fund-request',views.relief_fund_request,name="relief-fund-request"),
    path('fund-request/<int:public_id>/',views.fund_request,name="fund-request"),
    path('gov-dashboard',views.gov_dashboard,name="gov-dashboard"),
    path('update-public-profile/<int:public_id>/',views.update_public_profile,name="update-public-profile"),
    path('police-profile',views.police_profile,name="police-profile"),
    path('rescue-register',views.rescue_register,name="rescue-register"),
    path('rescue-login',views.rescue_login,name="rescue-login"),
    path('rescue-dashboard',views.rescue_dashboard,name="rescue-dashboard"),
    path('rescue-profile',views.rescue_profile,name="rescue-profile"),
    path('volunteer-profile',views.volunteer_profile,name="volunteer-profile"),
    path('camp-profile',views.camp_profile,name="camp-profile"),
    path('update-volunteer-profile/<int:volunteer_id>/',views.update_volunteer_profile,name="update-volunteer-profile"),
    path('insurance-profile',views.insurance_profile,name="insurance-profile"),
    
]
